name: CD

on:
  release:
    types:
      - published

env:
  NODE_VERSION: 16
  GLF_PROJECT: ./projects/packages/generate-license-file

jobs:
  get-version:
    name: Get Version

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }}

    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

  ci:
    needs:
      - get-version
    name: Run CI
    uses: ./.github/workflows/ci.yml
    with:
      version: ${{ needs.get_version.outputs.version }}
    secrets: inherit

  deploy:
    needs:
      - get-version
      - ci

    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Get Latest Tag
        uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: ${{ env.GLF_PROJECT }}/package.json

      - name: Download Packed Build
        uses: actions/download-artifact@v3
        with:
          name: Packed-Build
          path: ${{ env.GLF_PROJECT }}

      - name: Publish
        run: npm publish ${{ env.GLF_PROJECT }}/generate-license-file-${{ needs.get_version.outputs.version }}.tgz --access public --tag ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
