name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]
        exclude:
          # Temporarily excluded until migration to monorepo is completed.
          - os: windows-latest
            node: 14

    runs-on: ${{ matrix.os }}

    name: CI on ${{ matrix.os }} using Node ${{ matrix.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        if: matrix.node == 14
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint . --max-warnings 0

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        if: matrix.os == 'ubuntu-latest' && matrix.node == '18'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

  website-ci:
    runs-on: ubuntu-latest

    name: Website CI

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install library dependencies
        run: npm ci

      - name: Install website dependencies
        run: npm ci
        working-directory: ./website

      - name: Build docs site
        run: npm run build
        working-directory: ./website

      - name: Check for git changes
        run: git diff --exit-code
