name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]

    runs-on: ${{ matrix.os }}

    name: CI on ${{ matrix.os }} using Node ${{ matrix.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        if: matrix.node == 14
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint . --max-warnings 0

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v3.0.0
        if: matrix.os == 'ubuntu-latest' && matrix.node == '18'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
