name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint ./src --max-warnings 0

    - name: Build
      run: npm run build
      
    - name: Install dependencies for test project all-have-licenses
      run: npm ci
      working-directory: ./e2e/test-projects/all-have-licenses

    - name: Install dependencies for test project missing-license-file
      run: npm ci
      working-directory: ./e2e/test-projects/missing-license-file
    
    - name: Run Tests
      run: npm run test:ci
    
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: coverage
