name: npm build and publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - id: get_version
        uses: battila7/get-version-action@v2

      - run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint ./src --max-warnings 0

      - name: Build
        run: npm run build
        
      - name: Install dependencies for test project all-have-licenses
        run: npm ci
        working-directory: ./e2e/test-projects/all-have-licenses

      - name: Install dependencies for test project missing-license-file
        run: npm ci
        working-directory: ./e2e/test-projects/missing-license-file
      
      - name: Run Tests
        run: npm run test:ci
      
      - uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: ./package.json
      
      - run: npm publish --access public --tag ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
