name: Website CD

on:
  push:
    branches: [main]

jobs:
  website-cd:
    runs-on: ubuntu-latest

    name: Website CD

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        working-directory: ./website

      - name: Run Prettier
        run: npx prettier --check ./website

      - name: Run ESLint
        run: npx eslint ./website --max-warnings 0

      - name: Build
        run: npm run build
        working-directory: ./website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
